// Import Electron modules used to control the application
// and create native desktop windows.
import { app, BrowserWindow, Tray, nativeImage } from "electron";
import { createMainWindow } from "./windows/mainWindow.js";
import { createTimerWindow } from "./windows/timerWindow.js";
import { ipcMain, Notification, dialog } from "electron";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import pkg from "electron-updater";


const __dirname = path.dirname(fileURLToPath(import.meta.url));
const iconsDir = path.join(__dirname, "icons");

const appIconPath =
  process.platform === "win32"
    ? path.join(iconsDir, "icon.ico")
    : path.join(iconsDir, "icon.png");

// Windows: must match build.appId so the taskbar groups and shows the right icon.
app.setAppUserModelId("com.bettereveryday.app");

const { autoUpdater } = pkg;
    // Profile data persistence
    // ------------------------------------------------------
    // The user's profile (name, titles, bio, photo) lives in its own
    // folder inside Electron's userData directory, as a small JSON file
    // on disk — separate from anything else the app stores, and
    // reachable across app restarts/updates like the rest of the app's
    // saved data.
    //   <userData>/profile/profile.json
    const PROFILE_DIR = () => path.join(app.getPath("userData"), "profile");
    const PROFILE_FILE = () => path.join(PROFILE_DIR(), "profile.json");

    // This is what shows up as the sender name on notifications (instead
    // of the generic "Electron"), in the taskbar, and in userData paths.
    app.setName("BetterEveryDay");

function setupAutoUpdater()
    {
        autoUpdater.autoDownload = true;

        // Fired once the update has fully downloaded and is ready to
        // install. This is where the user gets asked, matching the
        // "always tell them" decision — never applied silently.
        autoUpdater.on("update-downloaded", (info) =>
        {
            dialog.showMessageBox({
                type: "info",
                title: "Update Ready",
                message: `A new version of Better Every Day (${info.version}) has been downloaded.`,
                detail: "Restart now to install it, or keep working and it'll apply the next time you close the app.",
                buttons: ["Restart Now", "Later"],
                defaultId: 0,
                cancelId: 1,
            }).then((result) =>
            {
                if (result.response === 0)
                {
                    autoUpdater.quitAndInstall();
                }
            });
        });

        // Non-fatal — if the update check fails (no internet, GitHub
        // unreachable, etc.), the app should just continue running
        // normally rather than interrupting the user.
        autoUpdater.on("error", (error) =>
        {
            console.error("[main] auto-updater error:", error);
        });

        try
        {
            autoUpdater.checkForUpdates();
        }
        catch (error)
        {
            // electron-updater throws synchronously here (not via the
            // "error" event above) when there's no app-update.yml to
            // read — which is always the case in dev, since that file
            // is only generated by electron-builder for packaged
            // builds. Without this catch, `npm run dashboard` crashes
            // on startup every time.
            console.error("[main] auto-updater failed to start:", error);
        }
    }

        // Wait until Electron has finished starting before
        // creating the application's main window.
    app.whenReady().then(() =>
    {
            //creates mainWindow for application
        createMainWindow();

        // Check for updates once the app has started — but only in
        // packaged builds. There's no update feed to check in dev,
        // and electron-updater isn't meant to run against an
        // unpackaged build anyway. Runs once per launch; if a newer
        // version is on GitHub, this kicks off the silent background
        // download.
        if (app.isPackaged)
        {
            setupAutoUpdater();
        }
       
    });

    ipcMain.on("open-timer", () =>
        {
            createTimerWindow();
        });
    
     ipcMain.on("window-minimize", (event) =>
        {
            const sourceWindow = BrowserWindow.fromWebContents(event.sender);
            if (sourceWindow)
            {
                sourceWindow.minimize();
            }
        });

    ipcMain.on("window-maximize", (event) =>
        {
            const sourceWindow = BrowserWindow.fromWebContents(event.sender);
            if (sourceWindow)
            {
                if (sourceWindow.isMaximized())
                {
                    sourceWindow.unmaximize();
                }
                else
                {
                    sourceWindow.maximize();
                }
            }
        });

    // Fired by the timer window (via preload) the moment a countdown
    // hits zero. Shows a native OS notification with simple text.
    // `silent: true` because the notification *sound* is handled in the
    // renderer instead (see notificationSound.ts) -- that's what lets
    // users pick a preset or custom sound and control its volume,
    // which the OS notification sound can't do.
    ipcMain.on("timer-complete", (event, payload = {}) =>
        {
            console.log("[main] timer-complete received", payload);
            console.log("[main] Notification.isSupported():", Notification.isSupported());

            if (!Notification.isSupported())
            {
                console.warn("[main] Notification not supported on this platform/build — nothing will show.");
                return;
            }

            const notification = new Notification({
                title: payload.title || "Timer finished",
                body: payload.body || "Your timer is up.",
                silent: true,
            });

                // Clicking the notification brings the window that
                // finished the timer back into focus.
            notification.on("click", () =>
                {
                    const sourceWindow = BrowserWindow.fromWebContents(event.sender);
                    if (sourceWindow)
                    {
                        if (sourceWindow.isMinimized()) sourceWindow.restore();
                        sourceWindow.show();
                        sourceWindow.focus();
                    }
                });

            notification.on("show", () => console.log("[main] notification shown"));
            notification.on("failed", (_e, error) => console.error("[main] notification failed:", error));

            notification.show();
        });

    // Notification sound file picking/reading
    // ------------------------------------------------------
    // Two handlers back the "custom sound" option in
    // Settings > Notifications:
    //   - select-audio-file: opens a native file picker
    //   - read-audio-file: reads the chosen file and returns it
    //     as a base64 data URL, since Chromium's renderer won't
    //     load arbitrary file:// paths directly.
    const AUDIO_MIME_TYPES = {
        ".mp3": "audio/mpeg",
        ".wav": "audio/wav",
        ".ogg": "audio/ogg",
        ".m4a": "audio/mp4",
        ".flac": "audio/flac",
        ".aac": "audio/aac",
    };

    ipcMain.handle("select-audio-file", async (event) =>
        {
            const sourceWindow = BrowserWindow.fromWebContents(event.sender);

            const result = await dialog.showOpenDialog(sourceWindow, {
                title: "Choose a notification sound",
                properties: ["openFile"],
                filters: [
                    { name: "Audio files", extensions: ["mp3", "wav", "ogg", "m4a", "flac", "aac"] },
                ],
            });

            if (result.canceled || result.filePaths.length === 0) return null;
            return result.filePaths[0];
        });

    ipcMain.handle("read-audio-file", async (_event, filePath) =>
        {
            if (!filePath || typeof filePath !== "string") return null;

            try
            {
                const buffer = await fs.promises.readFile(filePath);
                const ext = path.extname(filePath).toLowerCase();
                const mime = AUDIO_MIME_TYPES[ext] || "audio/mpeg";
                return `data:${mime};base64,${buffer.toString("base64")}`;
            }
            catch (error)
            {
                console.error("[main] failed to read custom sound file:", error);
                return null;
            }
        });

    // Profile save/load
    // ------------------------------------------------------
    // Backs the Profile page. Reads/writes a single JSON file in its
    // own "profile" folder under userData (see PROFILE_DIR/PROFILE_FILE
    // above), rather than sharing storage with anything else.
    ipcMain.handle("profile:load", async () =>
        {
            try
            {
                const raw = await fs.promises.readFile(PROFILE_FILE(), "utf-8");
                return JSON.parse(raw);
            }
            catch (error)
            {
                // No profile saved yet (first run) — not a real error.
                if (error.code !== "ENOENT")
                {
                    console.error("[main] failed to read profile.json:", error);
                }
                return null;
            }
        });

    ipcMain.handle("profile:save", async (_event, profile) =>
        {
            try
            {
                await fs.promises.mkdir(PROFILE_DIR(), { recursive: true });
                await fs.promises.writeFile(PROFILE_FILE(), JSON.stringify(profile, null, 2), "utf-8");
                return true;
            }
            catch (error)
            {
                console.error("[main] failed to write profile.json:", error);
                return false;
            }
        });
    


        // Recreate the window if the application is activated
        // and no windows are currently open (primarily for macOS).
    app.on("activate", () =>
    {
        if (BrowserWindow.getAllWindows().length === 0)
        {
            createMainWindow();
        }
    });


        // Close the application once every window has been closed.
    app.on("window-all-closed", () =>
    {
        app.quit();
    });